apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a2ckxm9u1-java-quarkus
  janus-idp.io/tekton: a2ckxm9u1-java-quarkus
  backstage.io/kubernetes-id: a2ckxm9u1-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a2ckxm9u1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
